name: Release BastionBuddy

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write # Needed for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for version determination

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          if ! command -v zip &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y zip
          fi

      - name: Build release binaries
        run: make release
        env:
          VERSION: ${{ env.VERSION }}

      - name: Generate changelog
        id: changelog
        shell: bash
        run: |
          # Try to get the previous tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREVIOUS_TAG" ]; then
            # No previous tag found - list all commits
            CHANGELOG=$(echo -e "Initial release\n\nChangelog:\n$(git log --pretty=format:'* %s' --reverse)")
          else
            # Get changes since the previous tag
            CHANGELOG=$(echo -e "Changes since $PREVIOUS_TAG:\n$(git log --pretty=format:'* %s' $PREVIOUS_TAG..HEAD)")
          fi
          echo "CHANGELOG=$CHANGELOG" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          files: |
            builds/*.tar.gz
            builds/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
